### ISSUE TITLE
API 공개 요청

### ISSUE THREAD

**Issue by BasixKOR** [Gortana/Gortana#1]
안녕하세요. 베이직입니다.
고르타나에 API가 생기면 어떨까 싶어 써넣어봅니다.
RESTful한 API가 생기면 여러 프로그램에서 고르타나를 활용할 수 있을 것이라 생각합니다.

**Comment by Gortana** [comment]
BasixKOR님, 안녕하세요. Gortana Labs 입니다.

현재 Gortana의 API공개는 정해진 바가 없습니다. 하지만 Gortana의 능력을 많은 사람들이 사용할 수 있도록 하는 방안을 검토 중 입니다.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support
