### ISSUE TITLE
자연어 처리 방식 알고리즘의 개선 Improvement of natural language processing algorithms

### ISSUE THREAD

**Issue by RichVillage** [Gortana/Gortana#2]
안녕하세요, Telegram 에서 Gortana를 사용하고 있는 한 유저입니다.
어제 Gortana DeepThink 모드를 보고 정말로 놀랐습니다.

인공 지능이 저렇게 뛰어난, 사람과 비슷한, 아니 사람보다 더욱 뛰어난 표현력을 가지고 대화를 할 수 있다는 점에서 크게 놀랐습니다.

다만 인공 지능이 한국어에서 가장 어려워하는 부분, 자연어 처리 방식에서 약간의 오류를 보여주는 모습을 보였습니다.
다른 부분은 거의 완벽하게 작동하였으나 일부 조사 및 접속사의 표현 오류가 있었습니다.

이 부분만 완벽하게 고쳐지면 완벽한 인공 지능이 될 것 같습니다.

좋은 하루 되시길 바랍니다.

**Comment by Gortana** [comment]
RichVillage님, 안녕하세요. Gortana Labs 입니다.

Gortana는 국어 학습을 많이 하고있으나 직접 글을 만들어내는 특성상 자연어 부분의 오류는 더욱 학습이 진행되야만 해결될 수 있는 문제입니다. 더욱 완벽한 모습을 보여드릴 수 있도록 노력하겠습니다.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support

**Comment by RichVillage** [comment]
알겠습니다.
앞으로도 뛰어난 Gortana의 활약을 기대하겠습니다.

좋은 하루 되세요!

Rich Village.

**Comment by Gortana** [comment]
RichVillage님, 안녕하세요. Gortana Labs 입니다.

Gortana를 사용해주셔서 감사합니다. Gortana와 즐거운 시간 보내세요.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support
