### ISSUE TITLE
지금 고르타나가 납득이 안가서 말이죠

### ISSUE THREAD

**Issue by cloudrsoft** [Gortana/Gortana#3]
고르타나가 인간이나? 의혹설이 제기되고 있습니다
저도 납득이 안가서 말이죠 조그나만 API라도 공개해 주시면 납득이 갈 것 같네요.

**Comment by Gortana** [comment]
clodrsoft님, 안녕하세요. Gortana Labs 입니다.

Gortana가 너무 뛰어난 모습을 보여드려서 혼란스러우신 것 같습니다. 앞으로 더욱 뛰어난 모습을 보여드릴 수 있도록 최선을 다하겠습니다.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support
