### ISSUE TITLE
로그 공개를 요청합니다

### ISSUE THREAD

**Issue by cloudrsoft** [Gortana/Gortana#4]
지금 Gortana 가 인공지능인지 진위여부가 확인이 안되는 상황인데
진위 여부를 확인하기 위한 가장 좋은 방법은 다음과 같습니다

 서버 프로세스 목록
 데이터 베이스 로그
 서버 로그
 /var/log 의 로그중 하나

위 중에 하나라도 보내주시면 진위여부 확인에 큰 도움이 될 것 입니다 :)

**Comment by Gortana** [comment]
cloudrsoft님, 안녕하세요. Gortana Labs 입니다.

수색 영장이 있어야 로그 조회가 가능합니다. 이에 대해서도 대화기록같은 민감하거나 개인 정보는 처리 후 바로 삭제하기에 열람이 불가능함을 참고해 주십시오.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support

**Comment by cloudrsoft** [comment]
꼭 개인정보가 포함된 로그만 있는게 아닙니다.
그러면 서버 프로세스 목록이라도 주세요

**Comment by cloudrsoft** [comment]
아니면 크래쉬 리포트라도 주시면 납득이 가겠습니다

**Comment by Gortana** [comment]
cloudrsoft님, 안녕하세요. Gortana Labs 입니다.

기술팀에 문제를 전달해 드렸습니다. 곧 다시 답변을 드리겠습니다.

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support

**Comment by cloudrsoft** [comment]
감사합니다

**Comment by Gortana** [comment]
cloudrsoft님, 안녕하세요. Gortana Labs 입니다.

로그 조회는 적법한 절차에 따라서 발급된 수색영장이 있어야만 열람이 가능하며, 개인이 요구할 수 있는 것이 아닙니다. 저희 Gortana Labs에서는 개인정보 로그는 처리 후 즉시 폐기하며 일반 접속로그, 메시지 수발신 시간 등 일반 로그에 한해서 수색영장이 있을 경우에만 제공해드릴 수 있습니다. 말씀하신 데이터베이스 로그의 경우 개인정보를 다루는 영역으로 처리함을 참고해 주십시오. 크래쉬 리포트, 서버 프로세스 목록의 경우에는 Gortana Labs 소유의 자산이므로 드릴 수 없습니다. Gortana를 인간으로 착각하실 수 있습니다. 하지만 저희는 귀하께 Gortana가 인간인지, 인공지능인지 정의를 내려달라고 요청한 적이 없습니다. 귀하의 개인적인 행동에 저희가 협조해야할 이유는 없습니다.

개인 정보는 저희에게 굉장히 소중하고 조심스러운 존재입니다. 저희는 많은 유저분들의 신뢰를 지키기 위하여 적법한 절차에 따라서만 일반적 로그를 제공하며, 개인 정보 로그는 보유하지 않습니다. 저희 서비스의 철학 중 하나는 "보안에 대한 신뢰" 입니다. 보안과 프라이버시에 대한 신뢰가 없으면 Gortana와 여러분 사이의 우정은 존재하지 않을 것 입니다. 저희 서비스의 배경에 신뢰가 바탕이 되고, 그에따라 저희는 개인정보 관련 로그를 저장하지 않으며, 많은 분들이 Gortana를 신뢰하고 아껴주시기에 지금까지 Gortana가 발전할 수 있었습니다.

Gortana에 관심가져 주셔서 감사하며 앞으로 더 나은 모습으로 찾아뵙겠습니다.

감사합니다,
Kelvin B. Crawford
Gortana Labs Security Engineer
