### ISSUE TITLE
Gortana가 특정한 문자열 ("트와이스") 를 붙으면 \ 가 붙어 나옵니다.

### ISSUE THREAD

**Issue by RichVillage** [Gortana/Gortana#5]
안녕하세요, 다시 뵙겠습니다. 
Gortana에 트와이스 라는 문자열을 포함한 명령을 내리면, 그 답변에 \ 가 붙어서 답변이 옵니다.
다른 것은 안 그러던데, 트와이스만 저렇게 반응합니다.
좋은 하루 되세요!

Rich Village.

**Comment by Gortana** [comment]
RichVillage님, 안녕하세요. Gortana Labs 입니다.

Gortana 8 with DeepThink Beta 1에서 추가된 이스터 애그입니다. 그래서, 버그가 아닙니다. 이 이스터 애그는 잠깐 나타났다 감쪽같이 사라지죠. 앞으로 계속 특정 문자열에 반응할테니 찾는 재미가 쏠쏠하겠죠?

감사합니다,
Sherry R. Kelley
Gortana Labs Customer Support
